#!/bin/bash
VERSION="v0.5.7 24/01/2023"
#     Copyright (C) 2020 Angel. uGeek
#     ugeekpodcast@gmail.com
#     https://ugeek.github.io




if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "h" ]  
then
echo "
Modo de empleo: search [OPCIONES]

sx                   -> Google
sx   t               -> Traducción de una web con google translate
sx   tb              -> Traducción de una web con bing translate
sx   tt  idioma      -> Google translate. Idioma= es,en,fr,it,de, ... 
sx   tts idioma      -> Lee en voz alta desde Google translate. Idioma= es,en,fr,it,de, ...
sx   bm              -> Muestra y abre una url de tus Booknarks
sx   bm nº_bookmark  -> Lanza el Bookmark indicando el nº
sx   bmls            -> Lista todos los Bookmarks
sx   bma             -> Añade un Bookmark
sx   bmp             -> Añade desde tu portapapeles un Bookmark
sx   bme             -> Edita tus Bookmarks
sx   s  url_web      -> Buscar en una web. Site
sx   sbm             -> Buscar en una web de tus Bookmarks
sx   d               -> Duck Duck Go
sx   b               -> Bing
sx   yh              -> Yahoo
sx   yd              -> Yandex
sx   sp              -> StartPage
sx   y               -> YouTube
sx   tw              -> Twitter
sx   twt             -> Twitter tendencias
sx   i               -> Google Image
sx   m               -> Google Maps
sx   gh              -> GitHub
sx   gl              -> GitLab
sx   r               -> Reddit
sx   rs subreddit    -> SubReddit
sx   w               -> Wikipedia
sx   wl              -> Wallapop
sx   ax              -> AliExpress
sx   eb              -> ebay
sx   sf              -> Spotify
sx   dz              -> Deezer
sx   ym              -> YouTube Music
sx   p               -> Google Podcast
sx   dp              -> Dropbox Paper
sx   tl              -> Buscar y ver Canales en Telegram
sx   trello          -> Trello
sx   imdb            -> IMDB
sx   tm              -> TheMovieDb
sx   e               -> Abrir archivo de configuración, para cambiar el navegador
sx   nav             -> Cambiar de navegador. Ejem: sx nav brave
sx   terminal        -> Cambiar a navegador de terminal. Ejem: sx terminal y  | sx terminal n
sx   h, -h, --help   -> Ayuda

search "$VERSION"
 Copyright (C) 2020 Angel. uGeek
 ugeekpodcast@gmail.com
 https://ugeek.github.io
"
exit
fi

mkdir -p $HOME/.config/search/


SOFT=$(diff -q  /usr/bin/sx <(wget -q -O- https://raw.githubusercontent.com/uGeek/search/master/search 2>/dev/null))

if [ "$(cat ~/.config/search/last.log 2>/dev/null)" != "$(date +"%Y%m%d")" ]
then
echo $(date +"%Y%m%d") >  ~/.config/search/last.log
if [ "$SOFT" = "" ]
then
echo "" 2>/dev/null
else
echo
echo -e "\n\e[31mHay una nueva actualización de la aplicación\e[0m \e[1msearch\e[0m\n\t\e[92mva a procederse la instalación\e[0m\n"
sudo curl -L https://raw.githubusercontent.com/uGeek/search/master/search \
          -o /usr/bin/sx && sudo chmod +x /usr/bin/sx
clear	  
echo -e "\n\t\e[1msearch.\e[0m \e[92mVersión $(wget -q -O- https://raw.githubusercontent.com/uGeek/search/master/search | grep "VERSION=" | cut -d "=" -f2 | sed s'|"||'g) actualizada con éxito! \e[0m\n"	  
exit 0
fi
fi

if [ ! -f ~/.config/search/search.conf ]; then
mkdir -p ~/.config/search/
echo -e "#  search  "$VERSION"\n#\n#     Copyright (C) 2020 Angel. uGeek\n#     ugeekpodcast@gmail.com\n#     https://ugeek.github.io\n#\n\nBROWSER='"firefox"'\nDEFAULT='g'\nLANG='es'\nBOOKMARKS='"$(echo $HOME)"/.config/search/search.urls' # Necesario ruta completa" >  ~/.config/search/search.conf
touch ~/.config/search/search.engine
fi

source ~/.config/search/search.conf





if [ "$1" = "e" ]
then
   vi   ~/.config/search/search.conf
exit
fi

g="https://www.google.com/search?q="
t="https://translate.google.com/translate?hl=auto&sl=auto&tl="$LANG"&u="
i="https://www.google.com/search?tbm=isch&q="
gh="https://github.com/search?q="
w="https://en.wikipedia.org/wiki/Special:Search?search="
m="https://www.google.com/maps?q="
d="https://duckduckgo.com/?q="
sp="https://www.startpage.com/do/search?q="
eb="https://www.ebay.com/s+ch/?_nkw="
a="https://www.amazon.es/exec/obidos/external-search/?field-keywords="$(echo $INPUT | sed s'| |%20|'g)"&mode=blended" 
b="https://www.bing.com/search?setmkt=es-ES&q="
y="https://www.youtube.com/results?search_query="
yd="https://yandex.com/search/?text="
imdb="https://www.imdb.com/find?s=all&q="
trello="https://trello.com/search?q="
dz="https://www.deezer.com/search/"
sf="https://open.spotify.com/search/"
r="https://www.reddit.com/search?q="
rs="https://www.reddit.com/r/$2/search?q="
tt="https://translate.google.com/?source=ugeek/search#auto|$2|"
s="https://www.google.com/search?client=ugeek/search=&q=site%3A"$2"+"
tb="https://www.translatetheweb.com/?from=auto&to="$LANG"&ref=SERP&refd=www.bing.com&dl="$LANG"&rr=UC&a="
wl="https://es.wallapop.com/search?keywords="
ax="https://es.aliexpress.com/wholesale?"$LANG"Id=0&initiative_id=&SearchText="
p="https://podcasts.google.com/?q="
dp="https://paper.dropbox.com/#q="
ym="https://music.youtube.com/search?q="
gl="https://gitlab.com/search?utf8=✓&snippets=&scope=&repository_ref=&search="
tl="https://t.me/s/"
tw="https://twitter.com/search?q="
twt="https://twitter.com/i/trends"
tm="https://www.themoviedb.org/search?language="$LANG"&query="

MT=$(echo $1)

if [ "$1" = "" ]
then
   MT=$(echo $DEFAULT)    
fi

if [ "$MT" = "g" ]
then
    CMD="$BROWSER $g"
    MOTOR="Google"
fi

if [ "$MT" = "t" ]
then
    CMD="$BROWSER $t"
    MOTOR="Google Translate Web"
fi

if [ "$MT" = "i" ]
then
    CMD="$BROWSER $i"
    MOTOR="Google Image"
fi

if [ "$MT" = "gh" ]
then
    CMD="$BROWSER $gh"
    MOTOR="GitHub"
fi

if [ "$MT" = "w" ]
then
    CMD="$BROWSER $w" 
    MOTOR="Wikipedia"
fi

if [ "$MT" = "m" ]
then
    CMD="$BROWSER $m"
    MOTOR="Google Maps"
fi

if [ "$MT" = "d" ]
then
    CMD="$BROWSER $d"
    MOTOR="Duck Duck Go"
fi

if [ "$MT" = "eb" ]
then
    CMD="$BROWSER $eb"
    MOTOR="ebay"
fi

if [ "$MT" = "b" ]
then
    CMD="$BROWSER $b"
    MOTOR="Bing"
fi

if [ "$MT" = "y" ]
then
    CMD="$BROWSER $y"
    MOTOR="YouTube"
fi

if [ "$MT" = "yd" ]
then
    CMD="$BROWSER $y"
    MOTOR="Yandex"
fi

if [ "$MT" = "imdb" ]
then
    CMD="$BROWSER $imdb"
    MOTOR="IMDB"
fi

if [ "$MT" = "trello" ]
then
    CMD="$BROWSER $trello"
    MOTOR="Trello"
fi

if [ "$MT" = "sp" ]
then
    CMD="$BROWSER $sp"
    MOTOR="StartPage"
fi

if [ "$MT" = "dz" ]
then
    CMD="$BROWSER $dz"
    MOTOR="Deezer"
fi

if [ "$MT" = "sf" ]
then
    CMD="$BROWSER $s"
    MOTOR="Spotify"
fi

if [ "$MT" = "r" ]
then
    CMD="$BROWSER $r"
    MOTOR="Reddit"
fi

if [ "$MT" = "tt" ]
then
    CMD="$BROWSER $tt"
    MOTOR="Google Translate Text"
fi

if [ "$MT" = "rs" ]
then
    CMD="$BROWSER $rs"
    MOTOR="SubReddit"
fi

if [ "$MT" = "s" ]
then
    CMD="$BROWSER $s"
    MOTOR="en "$2" Site"
fi

if [ "$MT" = "tb" ]
then
    CMD="$BROWSER $tb"
    MOTOR="Bing Translate Web"
fi

if [ "$MT" = "ax" ]
then
    CMD="$BROWSER  $ax"
    MOTOR="AliExpress"
fi

if [ "$MT" = "wl" ]
then
    CMD="$BROWSER  $wl"
    MOTOR="Wallapop"
fi

if [ "$MT" = "p" ]
then
    CMD="$BROWSER  $p"
    MOTOR="Podcast"
fi

if [ "$MT" = "dp" ]
then
    CMD="$BROWSER  $dp"
    MOTOR="Dropbox Paper"
fi

if [ "$MT" = "ym" ]
then
    CMD="$BROWSER  $ym"
    MOTOR="YouTube Music"
fi

if [ "$MT" = "gl" ]
then
    CMD="$BROWSER  $gl"
    MOTOR="GitLab"
fi

if [ "$MT" = "tl" ]
then
    CMD="$BROWSER  $tl"
    MOTOR="Telegram"
fi

if [ "$MT" = "tw" ]
then
    CMD="$BROWSER  $tw"
    MOTOR="Twitter"
fi


if [ "$MT" = "twt" ]
then
    CMD="$BROWSER  $twt"
    MOTOR=" Tendencias de Twitter"
    nohup $CMD 2>/dev/null  &
    exit 1
fi

if [ "$MT" = "tm" ]
then
    CMD="$BROWSER $tm"
    MOTOR="TheMovieDb"
fi

if [ "$MT" = "tts" ]
then
    CMD="$BROWSER"
    MOTOR="lee en voz alta desde tts de Google"
    echo -en "\n \e[1mSearch\e[0m \e[31m$MOTOR\e[0m: "
    read INPUT    
    nohup $CMD "https://translate.google.com/translate_tts?ie=UTF-8&total=1&idx=0&textlen=32&client=tw-ob&q="$(echo $INPUT | sed s'| |+|'g)"&tl=$2" 2>/dev/null  &
    exit 1
fi

if [ "$MT" = "bma" ]
then
    echo -en "\n \e[31mAñade un Bookmarks\e[0m"
    echo -en "\n\n   \e[1mNombre:\e[0m "
    read NOM
    echo -en "   \e[1murl:    \e[0m"
    read URL
    echo ""$URL" "$NOM"" >>  $BOOKMARKS 
    exit 1
fi

if [ "$MT" = "bm" ]
then
if [ "$2" = "" ]
then
    CMD="$BROWSER"
    MOTOR="Seleccina el Bookmarks"
    echo ""
    echo -e "    \e[4mListado de Bookmarks\e[0m"
    cat  $BOOKMARKS | cut -d" " -f2- | nl -s ". " | sed '/^ *$/d'
    echo -en "\n \e[1mSearch\e[0m \e[31m$MOTOR\e[0m: "
    read INPUT
    if [ "$TERMINAL" = "y" ] ; then   $CMD $(cat  $BOOKMARKS | cut -d" " -f1  | sed -n "$INPUT"p) ; exit  ; fi
    nohup $CMD $(cat  $BOOKMARKS | cut -d" " -f1  | sed -n "$INPUT"p) 2>/dev/null &
    exit 1
else
    CMD="$BROWSER"
    if [ "$TERMINAL" = "y" ] ; then   $CMD $(cat  $BOOKMARKS | cut -d" " -f1  | sed -n "$INPUT"p) ; exit  ; fi
    nohup $CMD $(cat  $BOOKMARKS | cut -d" " -f1  | sed -n "$INPUT"p) 2>/dev/null &
    exit 1
fi
fi


if [ "$MT" = "bmls" ]
then

    if [ "$2" = "" ] ; then
    echo ""
    echo -e "    \e[4mListado de Bookmarks\e[0m"
    cat  $BOOKMARKS | cut -d" " -f2- | nl -s ". " | grep -i "$2" | sed '/^ *$/d' 
    exit
    fi
    
    echo ""
    echo -e "    \e[4mListado de Bookmarks\e[0m"
    cat  $BOOKMARKS | cut -d" " -f2- | nl -s ". " | grep -i "$2" | sed '/^ *$/d' 
    echo -en "\n \e[1mSearch\e[0m \e[31m$MOTOR\e[0m: "
    read INPUT
    CMD="$BROWSER"
    if [ "$TERMINAL" = "y" ] ; then   $CMD $(cat  $BOOKMARKS | cut -d" " -f1  | sed -n "$INPUT"p) ; exit  ; fi
    nohup $CMD $(cat  $BOOKMARKS | cut -d" " -f1  | sed -n "$INPUT"p) 2>/dev/null &
    exit
fi


if [ "$MT" = "bme" ]
then
    $EDITOR  $BOOKMARKS 
    exit 1
fi

if [ "$MT" = "bmp" ]
then
    COPY=$(xclip -o)
    NAME=$(wget -q -O- $(echo $COPY) | sed -n 's/.*<title>\(.*\)<\/title>.*/\1/ip;T;q')
    echo -en "\n\e[31mLa siguiente página será añadida a Bookmarks\e[0m \n"
    echo -e "\e[1mNombre: \e[0m$NAME\n\e[1murl:    \e[0m$COPY"
    echo ""
    while true; do
        echo ""
        read -rp "¿Quieres añadir una anotación sobre la url? (s/n) " yn
        case "${yn}" in
            [Ss]* ) echo -en "\n Nota: "
		    read NOTE ; echo "$COPY $NAME - $NOTE" >> $BOOKMARKS
		    break;;
            [Nn]* ) echo "$COPY $NAME" >> $BOOKMARKS ; exit;;
            * ) echo "Please answer y or n";;
        esac
    done
    exit 1
fi

if [ "$MT" = "sbm" ]
then
    CMD="$BROWSER"
    MOTOR="Introduce las palabras que quieres buscar"
    echo ""
    echo -e "    \e[4mListado de Bookmarks\e[0m"
    cat  $BOOKMARKS | cut -d" " -f2- | nl -s ". " | sed '/^ *$/d'
    echo -en "\n \e[31mSeleccina en que url quieres buscar\e[0m: "
    read URL
    SITE="https://www.google.com/search?client=ugeek/search=&q=site%3A"$(cat $BOOKMARKS | cut -d" " -f1  | sed -n ""$URL""p)"+"
    CMD="$BROWSER $SITE"
fi

if [ "$MT" = "a" ]
then
    CMD="$BROWSER"
    MOTOR="Amazon"
    echo -en "\n \e[1mSearch\e[0m \e[31m$MOTOR\e[0m: "
    read INPUT    
    nohup $CMD "https://www.amazon.es/exec/obidos/external-search/?field-keywords="$(echo $INPUT | sed s'| |%20|'g)"&mode=blended" 2>/dev/null &
    exit 1
fi

if [ "$MT" = "yh" ]
then
    CMD="$BROWSER"
    MOTOR="Yahoo"
    echo -en "\n \e[1mSearch\e[0m \e[31m$MOTOR\e[0m: "
    read INPUT
    nohup $CMD "https://search.yahoo.com/search?p="$(echo $INPUT | sed s'| |%20|'g)"&ei=UTF-8" 2>/dev/null &
    exit 1
fi



if [ "$1" = "nav" ]
then    
echo "Cambiando al navegador $2"
sed -i "s|^BROWSER=.*|BROWSER='$2'|" $HOME/.config/search/search.conf
exit
fi

if [ "$1" = "terminal" ]
then
echo "Versión de terminal=$2"
sed -i "s|^TERMINAL=.*|TERMINAL='$2'|"  $HOME/.config/search/search.conf
exit
fi



source ~/.config/search/search.engine

if [ "$MOTOR" = "" ]
then
echo -en "\n\tEjecuta la opción -h o --help para ver la ayuda\n\n\t\t search -h\n"
exit
fi



echo -en "\n \e[1mSearch\e[0m \e[31m$MOTOR\e[0m: "
read INPUT

if [ "$TERMINAL" = "y" ] ; then    $CMD$(echo $INPUT | sed s'| |%20|'g) ; exit  ; fi
nohup $CMD$(echo $INPUT | sed s'| |%20|'g) 2>/dev/null &

exit 1
